openapi: 3.0.3
info:
  title: ModerationBusinessService
  description: Service that moderates the reviews to be posted
  version: 1.0.0
servers:
  - url: https://moderation-logic/api/v1
paths:
  /:
    post:
      summary: Censor review
      description: Censors the review to be posted
      operationId: censorReview
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        '200':
          description: review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Invalid input

  
components:
  schemas:
     Review:
      description: corpus of the review
      properties:
        corpus:
          type: string
